// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYMXwv4zzt8v-NUYc5PtYeR9SUKStxhUA',
    appId: '1:237000125461:web:a00471353d3829b683f21c',
    messagingSenderId: '237000125461',
    projectId: 'flutter-memo-app-d6448',
    authDomain: 'flutter-memo-app-d6448.firebaseapp.com',
    storageBucket: 'flutter-memo-app-d6448.appspot.com',
    measurementId: 'G-B3RDZ6VP6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8qiUVv6jVXe_NjQvn8XKy4Jq9-9T_IJU',
    appId: '1:237000125461:android:743aebe2e83dd1e583f21c',
    messagingSenderId: '237000125461',
    projectId: 'flutter-memo-app-d6448',
    storageBucket: 'flutter-memo-app-d6448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAInboU2ddX5Q1Fx0_x9upjvaoN3b-IrlI',
    appId: '1:237000125461:ios:a716d3897fb195da83f21c',
    messagingSenderId: '237000125461',
    projectId: 'flutter-memo-app-d6448',
    storageBucket: 'flutter-memo-app-d6448.appspot.com',
    iosClientId: '237000125461-9ba8iegpi2dqv8rginkadet1phpipjse.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseMemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAInboU2ddX5Q1Fx0_x9upjvaoN3b-IrlI',
    appId: '1:237000125461:ios:a716d3897fb195da83f21c',
    messagingSenderId: '237000125461',
    projectId: 'flutter-memo-app-d6448',
    storageBucket: 'flutter-memo-app-d6448.appspot.com',
    iosClientId: '237000125461-9ba8iegpi2dqv8rginkadet1phpipjse.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseMemoApp',
  );
}
